### ISSUE TITLE
Task: Define discussion prompts and questions based on post-experience survey answers

### ISSUE THREAD

**Issue by iolyd** [CUPUM/ia-ux-inclusif#10]
# Task Description

The survey can be accessed here: https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=7O9-0kcq50uYHg-Jd_ox2JHwCyAt1kZDpRqJWpGGuuRUNDhYVTJaVE1FWTlFTE9UODlIWktCTkQ0Vi4u&Token=ac0574b5b7034268b9527205f0166303

# List of actions

- [x] Scan through survey answers
- [x] Outline questions and discussion prompts
- [x] Submit everything for Friday oct. 27th at the latest

# Points extracted

- Manque d'étape de confirmation du choix.

- Manque de clarté pour communiquer la possibilité de modifier une réponse antérieure. Pourtant beaucoup d'énergie dépensée d'un point de vue technique pour intégrer cette fonctionnalité.

- Manque de nuance dans l'interaction avec la glissière: comment indiquer un choix au centre? Même si ce ne sont pas des données pertinentes dans le cadre de l'entraînement de l'IA, il s'agit d'une dimension expérientielle importante.

- Zone de clic ne pardonne pas assez, trop petite (checkboxes). En combinaison avec manque d'étape de confirmation de la glissière = évaluations erronées.
