### ISSUE TITLE
Task: Commander nourriture pour atelier du 1er décembre

### ISSUE THREAD

**Issue by iolyd** [CUPUM/ia-ux-inclusif#16]
# Task Description

- https://www.locallocal.ca/
- 10 personnes

## Détails de la commande

<img width="601" alt="Screenshot 2023-11-22 at 11 09 26 AM" src="https://github.com/CUPUM/ia-ux-inclusif/assets/52970928/66f3c4a6-f698-420e-9ecc-6f381c639be2">

# List of actions

- [x] Déterminer nombre de participants
- [x] Déterminer quels fonds utiliser pour payer le fournisseur
- [x] Préparer et passer la commande
- [x] Payer le fournisseur
- [x] Réceptionner la commande
