### ISSUE TITLE
Task: Définir des personas comme appui aux activités de l'atelier

### ISSUE THREAD

**Issue by iolyd** [CUPUM/ia-ux-inclusif#18]
# Task Description

L'atelier de co-design autour de la plateforme de labélisation propose différentes activités, dont certaines s'appuient sur l'utilisation de personas. Cette formule d'activité est assez courante dans le domaine du UX et facilite le travail des participants en leur permettant d'ancrer leurs réflexions et discussions sur des profils fictif mais réalistes qui soulèvent des enjeux importants dans le contexte du projet.

## Caractéristiques typiques d'un persona

- Name, age, gender, and a photo
- Tag line describing what they do in “real life”; avoid getting too witty, as doing so may taint the persona as being too fun and not a useful tool
- Experience level in the area of your product or service
- Context for how they would interact with your product: Through choice or required by their job? How often would they use it? Do they typically use a desktop computer to access it, or their phone or other device?
- Goals and concerns when they perform relevant tasks: speed, accuracy, thoroughness, or any other needs that may factor into their usage
- Quotes to sum up the persona’s attitude

## Données référence

Tel que discuté lors de https://github.com/CUPUM/ai-edi-space/issues/232, la création des personas peut se baser sur des combinaisons aléatoires de données recueillies dans le formulaire d'auto-identification.

[Données du formulaire d'auto-identification (accès privé)](https://udemontreal-my.sharepoint.com/:x:/g/personal/toumadher_ammar_umontreal_ca/ERK5CP8nFwZAkQGm2hvsAA0BdKqSfToTkItg-Qo1x9kGmg?email=emmanuel.beaudry.marchand%40umontreal.ca&e=4%3AqSD2yR&fromShare=true&at=9)

# List of actions

- [x] Voir avec @toumadher22 et @rsdmu si disponible pour collaboration sur montage des personas
- [ ] S'assurer que les noms des personas ne correspondent aucunement aux noms réels de participants
- [ ] Coordonner travail sur les personas avec Julie
- [ ] Produire documentation finale pour atelier

**Comment by iolyd** [comment]
Salut @toumadher22 et @rsdmu. Pour l'atelier du 1er décembre, Julie propose certaines activités qui s'appuient sur des _personas_. Préparer le contenu de ces activité implique entre autres d'élaborer 3-5 personas qui présentent des profils variés d'utilisateurs potentiels de l'application de labélisation. Pour respecter l'anonymat des participant.e.s au maximum, j'éviterais de simplement transposer le profil de certain.e.s d'entre eux.elles et approcherais la tâche plutôt en composant des profils appuyés à la fois sur des caractéristiques des participants et sur des caractéristiques hypothétiques soulevées par la demande de financement du projet (proposition ouverte à discussion).

Je sais que vous êtes bien occupé.e.s ces temps-ci, mais je voulais vérifier avec vous s'il serait possible qu'on se réserve une petite heure cette semaine pour aborder cette tâche. Sinon, seriez-vous en mesure de simplement me partager une liste d'éléments clés que vous aimeriez voir dans les _personas_, sachant qu'ils devraient idéalement quand même permettre de prévoir des défis d'utilisation vécus par les participants réels de l'activité de labélisation? Merci!

**Comment by toumadher22** [comment]
Bonjour Emmanuel oui volontiers nous pouvons volontiers prévoir une petite heure pour travailler dessus et comprendre un peu plus la façon dont devraient être montés les personas. Merci !

**Comment by rsdmu** [comment]
Hi @iolyd, 

Yes, I am available. 

For the profiles, I don't know how you guys define personas, nevertheless, following are some of the basic ideas:

- A person with shaky hands
- A person who has color blindness
- A person with limited vision
- A person not so at ease with tech.
- A person who can't understand well French/English

**Comment by iolyd** [comment]
Prévoir de détailler la _méthodologie_ de construction des _personas_ dans le compte rendu final du projet.

**Comment by iolyd** [comment]
Thanks @rsdmu, if you have more characteristics to propose, don't hesitate. Beyond that I think approaching the task using the self-identification form data should suffice.

@toumadher22, lorsque tu trouveras le temps, pourrais-tu me partager ici un lien vers le document excel avec les données anonymisées d'auto-identification des participants? Merci :)
