### ISSUE TITLE
Task: Rémunérer C. Sioui pour participation à l'atelier de co-design

### ISSUE THREAD

**Issue by iolyd** [CUPUM/ia-ux-inclusif#19]
# Task Description

Describe this task here

# List of actions

- [ ] Définir la rémunération totale
- [ ] Produire demande de paiement
- [ ] Assigner fonds du projet
