### ISSUE TITLE
Task: Define approach to data versioning

### ISSUE THREAD

**Issue by iolyd** [CUPUM/ia-ux-inclusif#29]
# Task Description

A particular challenge arises with using continuous development around Firebase data (NoSQL): we currently have no versioning of data structures and no up/down migration system. This can lead to problems both at the backend and frontend level when it comes to data validation and typings.

# List of actions

- [ ] Read on approaches to versioning and validation with Firebase
- [ ] Read on data typing with Firebase
- [ ] Implement changes progressively
- [ ] tbd...
